name: hermes
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.0

environment:
  sdk: ">=3.0.0 <3.24.5"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  package_info_plus: ^8.1.1
  device_info_plus: ^9.1.2
  cupertino_icons: ^1.0.5
  uuid: ^4.5.1
  toast: ^0.3.0
  provider: ^6.0.5
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_printer: ^2.0.3
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.15
  path: ^1.8.3
  archive: ^3.3.7
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  file_picker: ^8.1.4
  flutter_slidable: ^3.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.0.0
  fl_chart: ^0.69.0
  carousel_slider: ^5.0.0
  expressions: ^0.2.5+2

dev_dependencies:
  drift_dev: ^2.10.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
